# action.yml
name: 'Validate Home Assistant config'
description: ''
inputs:
  ha-version:
    description: 'Home Assistant Verison'
    required: true
    default: 'latest'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'docker://${{ inputs.ha-version }}'
  args:
    - python -m homeassistant --config ./config/ --script check_config --info all
