- platform: yr

# - platform: openweathermap
#   api_key: !secret owm_key
#   monitored_conditions:
#     - weather
#     - temperature
#     - wind_speed
#     - wind_bearing
#     - humidity
#     - pressure
#     - clouds
#     - rain
#     - snow

- platform: speedtestdotnet
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload