- platform: yr

# - platform: openweathermap
#   api_key: !secret owm_key
#   monitored_conditions:
#     - weather
#     - temperature
#     - wind_speed
#     - wind_bearing
#     - humidity
#     - pressure
#     - clouds
#     - rain
#     - snow

- platform: speedtest
  minute: 30
  hour:
    - 0
    - 3
    - 6
    - 9
    - 12
    - 15
    - 18
    - 21
  monitored_conditions:
    - ping
    - download
    - upload